# Generated by Django 5.2 on 2025-05-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='rating',
        ),
    ]
