# Generated by Django 5.2 on 2025-05-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='variation',
        ),
    ]
