# Generated by Django 5.2 on 2025-05-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=121232435),
            preserve_default=False,
        ),
    ]
