# Generated by Django 5.2 on 2025-05-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
