# Generated by Django 5.2 on 2025-05-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_quantiy_orderproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
